#!/usr/bin/python3
#
#      id.py  -  Convert list in file to dictionary
#
#
#
#

import sys
from collections import OrderedDict

#Make sure that there is a commandline arguement

if len(sys.argv) == 1 :
 print( "Please enter an argument" )
else :
 
 filename = sys.argv
 idList = open( filename[1] , "r")
 
 for line in idList :
  data = line.strip().split()

#compute average of all scored for student
  
  i = 1
  name = ""
  while i < len(data) :
   if name == "" :
    name = data[i]
   else :
    name = name + " "  + data[i]
   i += 1
  
  ID = dict()
  ID[ int(data[0]) ] = name
   
  for keys in sorted( ID ) :
   print (keys, ID[keys]) 
   
 

#Prints 2 columns (The name and The average)
#Puts outpu into file named from commandline arg.

#EOF


